- name: user
  hosts: all
  become: true
  tasks:
    - name: user create
      ansible.builtin.user:
        name: example
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: "/bin/bash"
        system: false
        create_home: true
        generate_ssh_key: true